# Generated by Django 4.2.2 on 2023-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(blank=True, null=True, to='CookApp.dish'),
        ),
    ]
