# Generated by Django 4.2.2 on 2023-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookApp', '0002_alter_ingredient_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.BooleanField(choices=[(0, 'Жидкое'), (1, 'Твердое')]),
        ),
    ]
